baseURL = 'https://cwlai21.github.io/'
languageCode = 'en-us'
title = 'Bon Courage'
theme = 'pehtheme-hugo'

paginate = '6' # <- Set the desired number of posts per page 
summaryLength = '20' # <- 20 words are approximately 160 characters
googleAnalytics = 'G-JJZXC5P9FV' # <- Your GA-4
disqusShortname = 'boncourage-1' # <- Get form here : https://disqus.com

[params]
	# Meta description, not exceeding 160 characters, used for the meta description within the HTML head
	description = 'Pehtheme Hugo Lite: A minimalist Hugo theme, built with TailwindCSS, for efficient performance and minimalism.'
	mainSections = 'posts'
	mermaid = true

[sitemap]
  changeFreq = 'weekly'
  disable = false
  filename = 'sitemap.xml'
  priority = -1

[author]
	name = 'Wendy Lai'
	bio = """
	La victoire appartient au plus opiniâtre. À cœur vaillant rien d'impossible.
	"""
#熱情會形成你的態度，而態度會決定高度，高度決定格局，格局又最終決定結局

	avatar = '/images/nasa-astronaut-unsplash.jpg'
	github = 'https://github.com/cwlai21'

[menu] # Menu management
	[[menu.main]]
		name = 'Home'
		pageRef = '/'
		weight = 10
	[[menu.main]]
		name = 'About'
		pageRef = '/about'
		weight = 15
	[[menu.main]]
		name = 'Category'
		pageRef = '/categories'
		weight = 25
	[[menu.main]]
		name = 'Tags'
		pageRef = '/tags'
		weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
  	source = 'assets'
  	target = 'static'

[permalinks]
post = "/:slug/"
page = "/:slug/"


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true